//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJDepthFirst2<R,A> extends GJDepthFirst<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   String presentfunc;
   
   
    String getregister(Integer t,int flag,int spill,int spnum){
           tobesent p = (tobesent)Final.get(presentfunc);
           HashMap<Integer,templiverange> q = p.tempsig;
	   templiverange b=q.get(t);
	   if(b!=null){
	   if( b.isallocatedreg==true)
		   return b.regallocated;
	   spill=1;
	   spnum=b.stacklocation;
	   if(flag!=-1)
		   System.out.println(" ALOAD v"+flag+" SPILLEDARG "+b.stacklocation+"\n");
	   return "v"+flag;
	   }
	   return "xx";
	   
   }
   
    String getregister1(Integer t,int flag,int[] spill,int[] spnum){
           tobesent p = (tobesent)Final.get(presentfunc);
           HashMap<Integer,templiverange> q = p.tempsig;
	   templiverange b=q.get(t);
	   if(b!=null){
	   if( b.isallocatedreg==true)
		   return b.regallocated;
	   spill[0]=1;
	   spnum[0]=b.stacklocation;
	   if(flag!=-1)
		   System.out.println(" ALOAD v"+flag+" SPILLEDARG "+b.stacklocation+"\n");
	   return "v"+flag;
	   }
	   return "xx";   
   }
   
   
   
   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         LinkedList<R> l = new LinkedList<R>();
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         l.add(e.nextElement().accept(this,argu));
            _count++;
         }
         return (R)l;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
       if ( n.present() ){
          n.node.accept(this,argu);
         
         return null;
         }
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return (R)n.tokenImage; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      Final = (HashMap<String,tobesent>)argu;
      n.f0.accept(this, argu);
      presentfunc="MAIN";
      tobesent p = Final.get("MAIN");
      System.out.println("MAIN [0] [" + (10+p.stackspilled) +"] ["+p.maxargcalls+"] \n");
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      System.out.println("END\n");
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n, A argu) {
      R _ret=null;
      argu = (A)"a";
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public R visit(Procedure n, A argu) {
      R _ret=null;
      argu = (A)"b";
      presentfunc = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
       Integer param=Integer.parseInt((String)n.f2.accept(this, argu));
       tobesent p = Final.get(presentfunc);
       if(p.maxargcalls>0){
            System.out.println(presentfunc+" ["+param+"]"+ "[" +(p.stackspilled+18) +"] ["+p.maxargcalls+"] \n");
             int i=0;
             int t=0;
            for(i=0;i<8;i++){
	    	  System.out.println("ASTORE SPILLEDARG "+(i+t)+" s"+i+"\n");
	      }
	      for(i=0;i<10;i++){
	    	  System.out.println("ASTORE SPILLEDARG "+(i+t+8)+" t"+i+"\n");
	      }
	      if(param>4)
	    	  t=param-4;
	      
	      for(i=0;i<4 &&i<param;i++){
	    	  	System.out.println("MOVE s"+i+" a"+i+"\n");
	      }
	    
       }
       else{
            int i=0;
            int t=0;
           System.out.println(presentfunc+" ["+param+"]"+ "[" +(p.stackspilled+10) +"] ["+p.maxargcalls+"] \n");
             for(i=0;i<10;i++){
	    	  System.out.println("ASTORE SPILLEDARG "+(i)+" t"+i+"\n");
	      }
	      if(param>4)
	    	  t=param-4;
	      
	      for(i=0;i<4 &&i<param;i++){
	    	  	System.out.println("MOVE s"+i+" a"+i+"\n");
	      }
       }
      int i=0,t=0;
        n.f3.accept(this, argu);
	 n.f4.accept(this, argu);
	    if(p.maxargcalls>0){   
	      for(i=0;i<8;i++){
	    	  System.out.println("ALOAD s"+i+" SPILLEDARG "+(i+t)+"\n");
	      }
	      for(i=0;i<10;i++){
	    	  System.out.println("ALOAD t"+i+" SPILLEDARG "+(i+t+8)+"\n");
	      }
       }
       else{
       for(i=0;i<10;i++){
	    	  System.out.println("ALOAD t"+i+" SPILLEDARG "+(i+t)+"\n");
	      }
       }
      System.out.println(" END\n");
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    */
   public R visit(Stmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
       System.out.println("NOOP\n");
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
       System.out.println("ERROR\n");
      return _ret;
   }


  
   /**
    * f0 -> "CJUMP"
    * f1 -> Temp()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String t=(String)n.f1.accept(this, argu);
      argu=(A)"b";
      String lab=(String)n.f2.accept(this, argu);
      int sp=0,spnum=-1;
      System.out.println(" CJUMP "+getregister(Integer.parseInt(t),1,sp,spnum)+" "+lab+"\n");
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
       argu=(A)"b";
       String S = (String)n.f1.accept(this, argu);
         System.out.println("JUMP "+S+"\n");
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Temp()
    * f2 -> IntegerLiteral()
    * f3 -> Temp()
    */
   public R visit(HStoreStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
       Integer t1=Integer.parseInt((String)n.f1.accept(this, argu));
      
      String literal=(String)n.f2.accept(this, argu);
      Integer t2=Integer.parseInt((String)n.f3.accept(this, argu));
      int sp1=0,sp2=0,spnum1=-1,spnum2=-1;
      String b=getregister(t1,0,sp1,spnum1);
      String c=getregister(t2, 1, sp2,spnum2);
      System.out.println(" HSTORE "+b+" "+literal+" "+c+"\n");
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Temp()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Integer t1=Integer.parseInt((String)n.f1.accept(this, argu));
      Integer t2=Integer.parseInt((String)n.f2.accept(this, argu));
      String literal=(String)n.f3.accept(this, argu);
      int[] sp1={0},sp2={0},spnum1={-1},spnum2={-1};
      String b1=getregister1(t1,0,sp1,spnum1);
      String b2=getregister1(t2,1,sp2,spnum2);
      
    	  System.out.println(" HLOAD "+b1+" "+b2+" "+literal+"\n");
      if(sp1[0]==1)
    	  System.out.println(" ASTORE SPILLEDARG "+spnum1[0]+" "+b1+"\n");
      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
       Integer t=Integer.parseInt((String)n.f1.accept(this, argu));
       argu=(A)t;
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public R visit(PrintStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
     String S = (String) n.f1.accept(this, argu);
     System.out.println(" PRINT "+S+"\n");
      return _ret;
   }

   /**
    * f0 -> Call()
    *       | HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   public R visit(Exp n, A argu) {
      R _ret=null;
      _ret = n.f0.accept(this, argu);
      
       if(n.f0.which==3){
    	  String b=(String)_ret;
    	  int[] sp={0},spnum={-1};
    	  String c=getregister1((Integer)argu,-1,sp,spnum);
    	  if(sp[0]==1)
    		  System.out.println("ASTORE SPILLEDARG "+spnum[0]+" "+b+"\n");
    	  
    	  else
    		  System.out.println("MOVE "+c+" "+b+"\n");
      }
      if(n.f0.which==1){
    	  String b=(String)_ret;
    	  int[] sp={0},spnum={-1};
    	  String c=getregister1((Integer)argu,0,sp,spnum);
    	  System.out.println(" MOVE "+c+" HALLOCATE "+b+"\n");
    	  if(sp[0]==1)
    		  System.out.println(" ASTORE SPILLEDARG "+spnum[0]+ " "+c+"\n");
      }
      if(n.f0.which==0){
    	  
    	  int[] sp={0},spnum={-1};
    	  String c=getregister1((Integer)argu,-1,sp,spnum);
    	  if(sp[0]==1)
    		  System.out.println(" ASTORE SPILLEDARG "+spnum[0]+" v0 \n");
    	  else
    		  System.out.println(" MOVE "+c+" v0\n");
    	  
      }
      return _ret;
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> SimpleExp()
    * f4 -> "END"
    */
   public R visit(StmtExp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String b = (String)n.f3.accept(this, argu);
      System.out.println(" MOVE v0 "+b+"\n");
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * f2 -> "("
    * f3 -> ( Temp() )*
    * f4 -> ")"
    */
   public R visit(Call n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String S = (String)n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      LinkedList<R> l=(LinkedList)n.f3.accept(this, argu);
      Iterator<R> iter=l.iterator();
       int sp=0,spnum=-1;String c;
      int ct=0;
      while(iter.hasNext()){
    	  
    	  sp=0;spnum=-1;
    	  c=getregister(Integer.parseInt((String)iter.next()),0,sp,spnum);
    	  if(ct<=3){
    		 
    			  System.out.println(" MOVE a"+ct+" "+c+"\n");
    		  }
    	  else
    	  {
    		  System.out.println(" PASSARG "+(ct-3)+" "+c+"\n");
    		  
    	  }
    	  ct++;
    	  
      }
      System.out.println(" CALL "+S+"\n");
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public R visit(HAllocate n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret=n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Operator()
    * f1 -> Temp()
    * f2 -> SimpleExp()
    */
   public R visit(BinOp n, A argu) {
      R _ret=null;
      String op = (String)n.f0.accept(this, argu);
      String temp = (String)n.f1.accept(this, argu);
      String s = (String)n.f2.accept(this, argu);
     
      int[] sp={0},spnum={-1};
      String c=getregister1(Integer.parseInt(temp),0,sp,spnum);
      sp[0]=0;spnum[0]=-1;
      String d=getregister1((Integer)argu,-1,sp,spnum);
      if(sp[0]==1)
    	  System.out.println(" MOVE v0 "+op+" "+c+" "+s+"\n"+" ASTORE SPILLEDARG "+spnum[0]+" v0\n");
      else
    	  System.out.println(" MOVE "+d+" "+op+" "+c+" "+s+"\n");
      return _ret;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public R visit(Operator n, A argu) {
      R _ret=null;
      String str="";
      n.f0.accept(this, argu);
      
      if(n.f0.which==0){
         str = " LE ";
      }
      else if(n.f0.which==1){
         str = " NE ";
      }
      else if(n.f0.which==2){
         str = " PLUS ";
      }
      else if(n.f0.which==3){
         str = " MINUS ";
      }
      else if(n.f0.which==4){
         str = " TIMES ";
      }
      else if(n.f0.which==5){
         str = " DIV ";
      }
      return (R)str;
   }

   /**
    * f0 -> Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(SimpleExp n, A argu) {
      R _ret=null;
       argu = (A)"b";
      _ret = n.f0.accept(this, argu);
      if(n.f0.which==0){
    	  int sp=0,spnum=-1;
    	  return (R)getregister(Integer.parseInt((String)_ret),1,sp,spnum);
      }
      if(n.f0.which==1){
    	  System.out.println(" MOVE v1 "+(String)_ret+"\n");
    	  return (R)"v1";
      }
      return _ret;
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public R visit(Temp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu); 
      _ret = n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return (R)n.f0.toString();
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n, A argu) {
      R _ret=null;
      String p =(String)n.f0.accept(this, argu);
      String S = (String)argu;
      if(S=="a"){
          System.out.println(p);
      }
      return (R)n.f0.toString();
   }

}
